# .air.toml

# Указываем корневую директорию проекта. "." означает текущую.
root = "."
# Временная директория для сборки.
tmp_dir = "/tmp"

[build]
# Команда для сборки приложения.
# Мы явно указываем путь к вашему main-пакету.
cmd = "go build -o /tmp/main ./cmd/microservice"
# Путь к скомпилированному бинарному файлу, который air будет запускать.
bin = "/tmp/main"
exclude_dir = ["tmp", "vendor"]
# Расширения файлов, за которыми нужно следить.
include_ext = ["go", "tpl", "tmpl", "html", "env"]
# Наблюдать за всеми поддиректориями.
#include_dir = ["."]

[log]
# Включить цвета в логах.
color = true